# -*- coding: utf-8 -*-
"""Task1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XOflQs4PJi8XazN74B-Jo4c2bB2wLYdw
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

df = pd.read_csv("Iris.csv")
print("First 5 Rows:\n", df.head())
print("\nDataset Info:\n")
print(df.info())
print("\nSummary:\n", df.describe())

df.columns = df.columns.str.strip().str.lower()
print(df.columns)

print("\nMissing Values:\n", df.isnull().sum())

df = df.drop('id', axis=1)
df

sns.pairplot(df, hue='species')
plt.show()

plt.figure()
sns.heatmap(df.drop(['species'], axis=1).corr(), annot=True)
plt.title("Correlation Heatmap")
plt.show()

from sklearn.model_selection import train_test_split
X = df.drop('species', axis=1)
y = df['species']
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)
print("Train shape:", X_train.shape)
print("Test shape:", X_test.shape)

from sklearn.ensemble import RandomForestClassifier
model = RandomForestClassifier(n_estimators=100, random_state=42)
model.fit(X_train, y_train)

from sklearn.metrics import accuracy_score
y_pred = model.predict(X_test)
print("Predictions:", y_pred[:5])
print("\nClassification Report:\n")
print(classification_report(y_test, y_pred))
print("Accuracy:", accuracy_score(y_test, y_pred))

plt.figure()
sns.heatmap(confusion_matrix(y_test, y_pred), annot=True, fmt='d')
plt.title("Confusion Matrix")
plt.xlabel("Predicted")
plt.ylabel("Actual")
plt.show()